ALTER TABLE "Invoice" ADD COLUMN "employeeCount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Invoice" ADD COLUMN "employeeAmount" DECIMAL(18,4) NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN "featureAmount" DECIMAL(18,4) NOT NULL DEFAULT 0;
